BestRestaurants/Models/BestRestaurantsContext.cs
using Microsoft.EntityFrameworkCore;

namespace BestRestaurants.Models
{
  public class BestRestaurantsContext : DbContext
  {
    public virtual DbSet<Cousine> CousineGroup { get; set; }
    public DbSet<Restaurant> RestaurantGroup { get; set; }

    public BestRestaurantsContext(DbContextOptions options) : base(options) { }
  }
}

BestRestaurants/Models/Cousine.cs
using System.Collections.Generic;

namespace BestRestaurants.Models
{
    public class Cousine
    {
        public Cousine()
        {
            this.RestaurantGroup = new HashSet<Restaurant>();
        }

        public int CousineId { get; set; }
        public string Name { get; set; }
        // public int RestaurantId { get; set; }
        public virtual ICollection<Restaurant> RestaurantGroup { get; set; }
    }
}

BestRestaurants/Models/Restaurants.cs
namespace BestRestaurants.Models
{
    public class Restaurant
    {
        public int RestaurantId { get; set; }
        public string Description { get; set; }

        public int CousineId { get; set; }
        public virtual Cousine Cousine { get; set; }
    }
}

BestRestaurants/Controllers/CousineController.cs
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace BestRestaurants.Controllers
{
  public class CousineGroupController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public CousineGroupController(BestRestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Cousine> model = _db.CousineGroup.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Cousine cousine)
    {
      _db.CousineGroup.Add(cousine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Cousine thisCousine = _db.CousineGroup.FirstOrDefault(cousine => cousine.CousineId == id);
      return View(thisCousine);
    }

    public ActionResult Edit(int id)
    {
      var thisCousine = _db.CousineGroup.FirstOrDefault(cousine => cousine.CousineId == id);
      return View(thisCousine);
    }

    [HttpPost]
    public ActionResult Edit(Cousine cousine)
    {
      _db.Entry(cousine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisCousine = _db.CousineGroup.FirstOrDefault(cousine => cousine.CousineId == id);
      return View(thisCousine);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCousine = _db.CousineGroup.FirstOrDefault(cousine => cousine.CousineId == id);
      _db.CousineGroup.Remove(thisCousine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult DeleteAll()
    {
      var allCousineGroup = _db.CousineGroup.ToList();
      return View();
    }

    [HttpPost, ActionName("DeleteAll")]
    public ActionResult DeleteAllConfirmed()
    {
      var allCousineGroup = _db.CousineGroup.ToList();

      foreach (var cousine in allCousineGroup)
      {
      _db.CousineGroup.Remove(cousine);
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurants/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace BestRestaurants.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }

    }
}

BestRestaurants/Controllers/RestaurantController.cs
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BestRestaurants.Controllers
{
    public class RestaurantGroupController : Controller
    {
        private readonly BestRestaurantsContext _db;

        public RestaurantGroupController(BestRestaurantsContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            List<Restaurant> model = _db.RestaurantGroup.Include(restaurantGroup => restaurantGroup.Cousine).ToList();
            return View(model);
        }

        public ActionResult Create()
        {
            ViewBag.CousineId = new SelectList(_db.CousineGroup, "CousineId", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Restaurant restaurant)
        {
            _db.RestaurantGroup.Add(restaurant);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Restaurant thisRestaurant = _db.RestaurantGroup.FirstOrDefault(restaurantGroup => restaurantGroup.RestaurantId == id);
            return View(thisRestaurant);
        }

        public ActionResult Edit(int id)
        {
            var thisRestaurant = _db.RestaurantGroup.FirstOrDefault(restaurantGroup => restaurantGroup.RestaurantId == id);
            ViewBag.CousineId = new SelectList(_db.CousineGroup, "CousineId", "Name");
            return View(thisRestaurant);
        }

        [HttpPost]
        public ActionResult Edit(Restaurant restaurant)
        {
            _db.Entry(restaurant).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var thisRestaurant = _db.RestaurantGroup.FirstOrDefault(restaurantGroup => restaurantGroup.RestaurantId == id);
            return View(thisRestaurant);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var thisRestaurant = _db.RestaurantGroup.FirstOrDefault(restaurantGroup => restaurantGroup.RestaurantId == id);
            _db.RestaurantGroup.Remove(thisRestaurant);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DeleteAll()
        {
            var allRestaurantGroup = _db.RestaurantGroup.ToList();
            return View();
        }

        [HttpPost, ActionName("DeleteAll")]
            public ActionResult DeleteAllConfirmed()
        {
            var allRestaurantGroup = _db.RestaurantGroup.ToList();

        foreach (var restaurant in allRestaurantGroup)
        {
            _db.RestaurantGroup.Remove(restaurant);
        }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BestRestaurants/Views/CousineGroup/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cousine

<h4>Add a new cousine type</h4>
<hr />
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    <button class="btn btn-success" type="submit">Add New Cousine Type</button>
}
<hr />
<p>@Html.ActionLink("Show all cousine types", "Index")</p>

BestRestaurants/Views/CousineGroup/Delete.cshtml
@{
  Layout = "_Layout";
}
<center>
@model BestRestaurants.Models.Cousine

<h1>Are you sure you want to delete @Html.DisplayFor(model => model.Name)?</h1>
<br>

@using (Html.BeginForm())
{
    <button class="btn btn-success" type="submit">Delete</button>
}
<hr>
<br>
<p>@Html.ActionLink("Back to cousine type list", "Index")</p>
</center>

BestRestaurants/Views/CousineGroup/DeleteAll.cshtml
@{
  Layout = "_Layout";
}
<center>
  @model List<BestRestaurants.Models.Cousine>;

<h2>Are you sure you want to delete all cousine types?</h2>
<br>

@using (Html.BeginForm())
{
    <center><button class="btn btn-success" type="submit" value="DeleteAll" />Delete All</center>
}

<br>
<br>
<p>@Html.ActionLink("Back to the cousine type list", "Index")</p>

</center>

BestRestaurants/Views/CousineGroup/Details.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;
@model BestRestaurants.Models.Cousine;
<center>
<h1>@Html.DisplayFor(model => model.Name) Cousine</h1>
<hr />
<ul>
@if (@Model.RestaurantGroup.Count == 0)
{
<p><i>No Restaurants found</i></p>
}

@foreach (Restaurant restaurant in @Model.RestaurantGroup)
{
  <ul><h4>Description: @restaurant.Description</h4></ul>
  Console.WriteLine("this");
}
</ul>
<hr />
@* <p>@Html.ActionLink("Add new restaurant", "Create", new { id = Model.RestaurantId })</p> *@
<p>@Html.ActionLink("Edit Cousine Type", "Edit", new { id = Model.CousineId })</p>
<p>@Html.ActionLink("Delete Cousine Type", "Delete", new { id = Model.CousineId })</p>
<p>@Html.ActionLink("Cousine Type Overview", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>
</center>

BestRestaurants/Views/CousineGroup/Edit.cshtml
@{
  Layout = "_Layout";
}
@model BestRestaurants.Models.Cousine
<center>
<h1>Edit</h1>
<br>
<hr>

<h4>Edit this cousine type: @Html.DisplayFor(model => model.Name)</h4>
<br>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.CousineId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    <button class="btn btn-success" type="submit">Save</button>
}
<hr>
<br>
<p>@Html.ActionLink("Cousine Type Overview", "Index")</p>

</center>

BestRestaurants/Views/CousineGroup/Index.cshtml
@{
  Layout = "_Layout";
}
<center>
@using BestRestaurants.Models;
@model List<BestRestaurants.Models.Cousine>;

<h1>Cousine Types</h1>
<br>
<hr />

@if (@Model.Count == 0)
{
<h4>No cousine types have been added yet!</h4>
}

@foreach (Cousine cousine in Model)
{
<h4>@Html.ActionLink($"{cousine.Name}", "Details", new { id = cousine.CousineId })</h4>
}

<hr />
<br> 
<p>@Html.ActionLink("Add New Cousine Type", "Create")</p>
<p>@Html.ActionLink("Delete All Cousine Types", "DeleteAll")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>
</center>

BestRestaurants/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}
<center>

<h1>My Favorite Seattle Restaurants</h1>
<br>
<h4>Add cousine type first!</h4>
<br>
<hr />
<br>
<p>@Html.ActionLink("Search by Cousine Type", "Index", "CousineGroup")</p>
<br>
<p>@Html.ActionLink("Search by Restaurant Name", "Index", "RestaurantGroup")</p>
</center>

BestRestaurants/Views/RestaurantGroup/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant
<center>
  
</center>
<h4>Add New Restaurant</h4>
<hr />

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Description)
    @* @Html.TextBoxFor(model => model.Name) *@
    @Html.TextBoxFor(model => model.Description)
    @Html.LabelFor(model => model.Cousine)
    @Html.DropDownList("CousineId")
    <br>
    <br>
    <button class="btn btn-success" type="submit">Add New Restaurant</button>
}
<hr />
<p>@Html.ActionLink("Restaurant Overview", "Index")</p>

BestRestaurants/Views/RestaurantGroup/Delete.cshtml
@{
  Layout = "_Layout";
}
@model BestRestaurants.Models.Restaurant
<center>
<h1>Are you sure you want to delete @Html.DisplayFor(model => model.Description)?</h1>
<br>
@using (Html.BeginForm())
{
    <button class="btn btn-success" type="submit">Delete</button>
}
<hr />
@Html.ActionLink("Back to List", "Index")
</center>

BestRestaurants/Views/RestaurantGroup/DeleteAll.cshtml
@{
  Layout = "_Layout";
}

<center>
  @model List<BestRestaurants.Models.Restaurant>;

  <h2>Are you sure you want to delete all restaurant list?</h2>
  <br>

  @using (Html.BeginForm())
  {
      <center><button class="btn btn-success" type="submit" value="DeleteAll" />Delete All</center>
  }

  <br>
  <br>
  <p>@Html.ActionLink("Restaurant Overview", "Index")</p>

</center>

BestRestaurants/Views/RestaurantGroup/Details.cshtml
@{
  Layout = "_Layout";
}
@model BestRestaurants.Models.Restaurant

<center>
<h1>Restaurant Details</h1>
<hr />

<h4>@Html.DisplayFor(model => model.Description)</h4>
<hr />
<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Restaurant", "Edit", new { id = Model.RestaurantId })</p>
<p>@Html.ActionLink("Delete Restaurant", "Delete", new { id = Model.RestaurantId })</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>
</center>

BestRestaurants/Views/RestaurantGroup/Edit.cshtml
@{
  Layout = "_Layout";
}
@model BestRestaurants.Models.Restaurant
<center>
<h1>Edit</h1>
<br>
<hr />
<h4>Edit this restaurant: @Html.DisplayFor(model => model.Description)</h4>
<br>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.RestaurantId)

    @Html.LabelFor(model => model.Description)
    @Html.EditorFor(model => model.Description)

    @Html.LabelFor(model => model.Cousine)
    @Html.DropDownList("CousineId")
    <button class="btn btn-success" type="submit">Save</button>
}
<hr />
<br>
<p>@Html.ActionLink("Back to list", "Index")</p>
</center>

BestRestaurants/Views/RestaurantGroup/Index.cshtml
@{
  Layout = "_Layout";
}
@using BestRestaurants.Models;
@model List<BestRestaurants.Models.Restaurant>;

<center>
<h1>Restaurants</h1>
<br>
<hr />

@if (@Model.Count == 0)
{
  <h4>No restaurants have been added yet!</h4>
}

@foreach (Restaurant restaurant in Model)
{
  <h4>@Html.ActionLink($"{restaurant.Description}", "Details", new { id = restaurant.RestaurantId }) | @restaurant.Cousine.Name</h4>
}

<hr />
<br>
<p>@Html.ActionLink("Add new restaurant", "Create")</p>
<p>@Html.ActionLink("Delete All restaurants", "DeleteAll")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

</center>

BestRestaurants/Views/Shared/Footer.cshtml
<div id="footer">My Favorite Restaurants</div>

BestRestaurants/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My favorite restaurants</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>

    @RenderBody()
    @Html.Partial("Footer")
  </body>
</html>